modLoader="javafml"
loaderVersion="${neoforgeLoaderVersionRange}"
issueTrackerURL="${githubUrl}/issues?q=is%3Aissue"
license="The MIT License (MIT)"

[[mods]]
modId="mezz_config_gui_test_neoforge_defaults"
version="${version}"
displayName="MezzConfig GUI NeoForge Native Defaults Test"
displayURL="${githubUrl}"
displayTest="IGNORE_SERVER_VERSION"
authors="${modAuthor}"
description='''
Default native NeoForge config screen test for MezzConfig GUI.
'''

[[dependencies.mezz_config_gui_test_neoforge_defaults]]
    modId="neoforge"
    type="required"
    versionRange="${neoforgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mezz_config_gui_test_neoforge_defaults]]
    modId="minecraft"
    type="required"
    versionRange="${minecraftVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mezz_config_gui_test_neoforge_defaults]]
    modId="${configGuiModId}"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"
